# Blocks a PR that adds a dependency with a known vulnerability (or a
# disallowed license). Cairn has a single runtime dep (elkjs), so this mostly
# guards devDependencies and future additions.
name: dependency-review
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with: { persist-credentials: false }
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          fail-on-severity: high
